# services
services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "4000:4000"
    # env_file: ./Backend/.env

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
    env_file: ./Frontend/.env
    # environment:
    #   - VITE_BASE_URL=$VITE_BASE_URL

